# Generated by Django 5.2.4 on 2025-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='itens_imagens/'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20),
        ),
    ]
