# Generated by Django 5.2.4 on 2025-07-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustomizado',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuariocustomizado',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuariocustomizado',
            name='telefone',
        ),
    ]
